syntax = "proto3";
package oj.demo.file.v1;

import "oj/demo/file/v1/file.proto";

message UploadFileTask {
  FileInfo file_info = 2;
  string upload_url = 3;
  int64 create_time = 4;
  int64 expire_time = 5;
}

message CreateUploadFileTaskRequest {
  int32 user_id = 1;
  string filename = 2;
  int64 size = 4;
  string mime_type = 5;
  HashType hash_type = 7;
  bytes hash = 8;
  bool has_token = 9;
}

enum UploadFileTaskStatus {
  UPLOAD_FILE_TASK_STATUS_UNSPECIFIED = 0;
  UPLOAD_FILE_TASK_STATUS_SUCCESS = 1;
  UPLOAD_FILE_TASK_STATUS_FAILED = 2;
  UPLOAD_FILE_TASK_STATUS_FILE_IS_EXIST = 3;
  UPLOAD_FILE_TASK_STATUS_SIZE_EXCEED_LIMIT = 4;
  UPLOAD_FILE_TASK_STATUS_TASK_HAS_EXIST = 5;
}

message CreateUploadFileTaskResponse {
  UploadFileTaskStatus status = 2;
  oneof result {
    UploadFileTask upload_file_task = 1;
    FileInfo file_info = 3;
  }
}

message FinishUploadFileTaskRequest {
  int64 upload_file_task_id = 1;
  bool success = 2;
}

enum FinishUploadFileTaskStatus {
  FINISH_UPLOAD_FILE_TASK_STATUS_UNSPECIFIED = 0;
  FINISH_UPLOAD_FILE_TASK_STATUS_SUCCESS = 1;
  FINISH_UPLOAD_FILE_TASK_STATUS_FAILED = 2;
  FINISH_UPLOAD_FILE_TASK_STATUS_SIZE_INVALID = 3;
  FINISH_UPLOAD_FILE_TASK_STATUS_HASH_MISMATCH = 4;
  FINISH_UPLOAD_FILE_TASK_STATUS_PERMISSION_DENIED = 5;
}

message FinishUploadFileTaskResponse {
  FinishUploadFileTaskStatus status = 1;
  optional FileInfo file_info = 2;
}

message GetFileGetUrlRequest {
  int64 file_id = 1;
  string token = 2;
  bool pre_sign = 3;
}

enum GetFileGetUrlStatus {
  GET_FILE_GET_URL_STATUS_UNSPECIFIED = 0;
  GET_FILE_GET_URL_STATUS_SUCCESS = 1;
  GET_FILE_GET_URL_STATUS_FILE_NOT_FOUND = 2;
  GET_FILE_GET_URL_STATUS_PERMISSION_DENIED = 3;
}

message GetFileGetUrlResponse {
  GetFileGetUrlStatus status = 1;
  string url = 2;
}

message DeleteFileRequest {
  int64 file_id = 1;
}

enum DeleteFileStatus {
  DELETE_FILE_STATUS_UNSPECIFIED = 0;
  DELETE_FILE_STATUS_SUCCESS = 1;
  DELETE_FILE_STATUS_FILE_NOT_FOUND = 2;
  DELETE_FILE_STATUS_PERMISSION_DENIED = 3;
}

message DeleteFileResponse {
  DeleteFileStatus status = 1;
  int64 expire_time = 2;
}

message GetUploadFileTaskRequest {
  int64 upload_file_task_id = 1;
}
message GetUploadFileTaskResponse {
  optional UploadFileTask upload_file_task = 1;
}

message AbortUploadFileTaskRequest {
  int64 upload_file_task_id = 1;
}

enum AbortUploadFileTaskStatus {
  ABORT_UPLOAD_FILE_TASK_STATUS_UNSPECIFIED = 0;
  ABORT_UPLOAD_FILE_TASK_STATUS_SUCCESS = 1;
  ABORT_UPLOAD_FILE_TASK_STATUS_TASK_NOT_FOUND = 2;
  ABORT_UPLOAD_FILE_TASK_STATUS_PERMISSION_DENIED = 3;
}

message AbortUploadFileTaskResponse {
  AbortUploadFileTaskStatus status = 1;
}

service FileService {
  rpc CreateUploadFileTask(CreateUploadFileTaskRequest) returns (CreateUploadFileTaskResponse);
  rpc FinishUploadFileTask(FinishUploadFileTaskRequest) returns (FinishUploadFileTaskResponse);
  rpc AbortUploadFileTask(AbortUploadFileTaskRequest) returns (AbortUploadFileTaskResponse);
  rpc GetFileGetUrl(GetFileGetUrlRequest) returns (GetFileGetUrlResponse);
  rpc DeleteFile(DeleteFileRequest) returns (DeleteFileResponse);
  rpc GetUploadFileTask(GetUploadFileTaskRequest) returns (GetUploadFileTaskResponse);
}
