syntax = "proto3";
package oj.demo.user.profile;

import "user.user.proto";

option java_package = "oj.demo.user.api.profile.update";
option java_multiple_files = true;

enum UpdateStatus {
    UPDATE_STATUS_SUCCESS = 0;
    UPDATE_STATUS_ARG_INVALID = 1;
}

message UpdateAvatarRequest {
    int64 file_id = 1;
}

message UpdateProfileResponse {
    UpdateStatus status = 1;
    UserProfile profile = 2;
}

service UpdateService {
    rpc UpdateProfile (UserProfile) returns (UpdateProfileResponse); 
    rpc UpdateAvatar (UpdateAvatarRequest) returns (UpdateProfileResponse);
}
