syntax = "proto3";
package oj.demo.user.v1;

message ChangePasswordRequest {
  string old_password = 1;
  string new_password = 2;
  string refresh_token = 3;
}

enum ChangeStatus {
  CHANGE_STATUS_UNSPECIFIED = 0;
  CHANGE_STATUS_OLD_PASSWORD_INCORRECT = 1;
  CHANGE_STATUS_ARGS_INVALID = 2;
  CHANGE_STATUS_TOO_MANY_REQUESTS = 3;
  CHANGE_STATUS_REFRESH_TOKEN_INVALID = 4;
}

message ChangePasswordResponse {
  ChangeStatus status = 1;
}

service ChangeService {
  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);
}
