syntax = "proto3";
package oj.demo.user.v1;

import "buf/validate/validate.proto";

message ChangePasswordRequest {
  string old_password = 1 [
    (buf.validate.field).string.min_len = 6,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-zA-Z0-9!@#$%^&*_]+$"
  ];
  string new_password = 2 [
    (buf.validate.field).string.min_len = 6,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-zA-Z0-9!@#$%^&*_]+$"
  ];
}

enum ChangeStatus {
  CHANGE_STATUS_UNSPECIFIED = 0;
  CHANGE_STATUS_OLD_PASSWORD_INCORRECT = 1;
  CHANGE_STATUS_ARGS_INVALID = 2;
  CHANGE_STATUS_TOO_MANY_REQUESTS = 3;
  CHANGE_STATUS_REFRESH_TOKEN_INVALID = 4;
}

message ChangePasswordResponse {
  ChangeStatus status = 1;
}

service ChangeService {
  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);
}
