syntax = "proto3";
package oj.demo.user.v1;

enum LoginType {
  LOGIN_TYPE_ID_UNSPECIFIED = 0;
  LOGIN_TYPE_EMAIL = 1;
}

message AccessTokenPayload {
  int32 user_id = 1;
  int32 user_profile_id = 2;
  int64 expipre = 5;
}

message LoginRequest {
  LoginType login_type = 1;
  oneof account {
    int32 id = 2;
    string email = 3;
  }
  string password = 4;
}

enum LoginStatus {
  LOGIN_STATUS_SUCCESS_UNSPECIFIED = 0;
  LOGIN_STATUS_PASSWD_INCORRECT = 1;
  LOGIN_STATUS_ACCOUNT_NOT_EXIST = 2;
  LOGIN_STATUS_ARGS_INVALID = 3;
  LOGIN_STATUS_TOO_MANY_REQUESTS = 4;
}

message LoginResponse {
  LoginStatus status = 1;
  int32 user_id = 2;
  string refresh_token = 3;
  string access_token = 4;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

enum RefreshTokenStatus {
  REFRESH_TOKEN_STATUS_SUCCESS_UNSPECIFIED = 0;
  REFRESH_TOKEN_STATUS_INVALID = 1;
  REFRESH_TOKEN_STATUS_ARGS_INVALID = 2;
  REFRESH_TOKEN_STATUS_TOO_MANY_REQUESTS = 3;
}

message RefreshTokenResponse {
  RefreshTokenStatus status = 1;
  int32 user_id = 2;
  string access_token = 3;
}

service LoginService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
}
