syntax = "proto3";
package oj.demo.user.v1;

import "buf/validate/validate.proto";

enum LoginType {
  LOGIN_TYPE_ID_UNSPECIFIED = 0;
  LOGIN_TYPE_EMAIL = 1;
}

message LoginRequest {
  LoginType login_type = 1;
  oneof account {
    int32 id = 2 [(buf.validate.field).int32.gt = 0];
    string email = 3 [(buf.validate.field).string.email = true];
  }
  string password = 4 [
    (buf.validate.field).string.min_len = 6,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-zA-Z0-9!@#$%^&*_]+$"
  ];
}

enum LoginStatus {
  LOGIN_STATUS_SUCCESS_UNSPECIFIED = 0;
  LOGIN_STATUS_PASSWD_INCORRECT = 1;
  LOGIN_STATUS_ACCOUNT_NOT_EXIST = 2;
  LOGIN_STATUS_ARGS_INVALID = 3;
  LOGIN_STATUS_TOO_MANY_REQUESTS = 4;
}

message LoginResponse {
  LoginStatus status = 1;
  int32 user_id = 2;
  string refresh_token = 3;
  string access_token = 4;
}

message RefreshTokenRequest {
  string refresh_token = 1;
}

enum RefreshTokenStatus {
  REFRESH_TOKEN_STATUS_SUCCESS_UNSPECIFIED = 0;
  REFRESH_TOKEN_STATUS_TOKEN_INVALID = 1;
  REFRESH_TOKEN_STATUS_ARGS_INVALID = 2;
  REFRESH_TOKEN_STATUS_TOO_MANY_REQUESTS = 3;
}

message RefreshTokenResponse {
  RefreshTokenStatus status = 1;
  int32 user_id = 2;
  string access_token = 3;
}

service LoginService {
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
}
