syntax = "proto3";
package oj.demo.user.v1;

import "buf/validate/validate.proto";

message LogoutRequest {
  //base64
  string refresh_token = 1 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 64,
    (buf.validate.field).string.pattern = "^[A-Za-z0-9+/]+={0,2}$"
  ];
}

enum LogoutStatus {
  LOGOUT_STATUS_SUCCESS_UNSPECIFIED = 0;
  LOGOUT_STATUS_INVALID_TOKEN = 1;
}

message LogoutResponse {
  LogoutStatus status = 1;
}

service LogoutService {
  rpc Logout(LogoutRequest) returns (LogoutResponse);
}
