syntax = "proto3";
package oj.demo.user.v1;

option java_multiple_files = true;
option java_package = "oj.demo.user.api.v1.register";

message RegisterRequest {
  string email = 1;
  string password = 2;
  string code = 3;
}

enum RegisterStatus {
  REGISTER_STATUS_SUCCESS_UNSPECIFIED = 0;
  REGISTER_STATUS_EMAIL_ALREADY_EXISTS = 1;
  REGISTER_STATUS_CODE_INVALID = 2;
  REGISTER_STATUS_ARGS_INVALID = 3;
  REGISTER_STATUS_TOO_MANY_REQUESTS = 4;
}

message RegisterResponse {
  RegisterStatus status = 1;
  int32 user_id = 2;
}
