syntax = "proto3";
package oj.demo.user.v1;

option java_multiple_files = true;
option java_package = "oj.demo.user.api.v1.reset";

enum AccountType {
  ACCOUNT_TYPE_UNSPECIFIED = 0;
  ACCOUNT_TYPE_ID = 1;
  ACCOUNT_TYPE_EMAIL = 2;
}

message ResetPasswordRequest {
  AccountType type = 1;
  string code = 2;
  string new_password = 3;
  int64 timestamp = 4;
  int32 nonce = 5;
}

enum ResetStatus {
  RESET_STATUS_UNSPECIFIED = 0;
  RESET_STATUS_SUCCESS = 1;
  RESET_STATUS_INVALID_CODE = 2;
  RESET_STATUS_EXPIRED_CODE = 3;
  RESET_STATUS_ARG_INVALID = 4;
}

message ResetPasswordResponse {
  ResetStatus status = 1;
  int32 user_id = 2;
}

service ResetService {
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
}
