syntax = "proto3";
package oj.demo.user.v1;

import "buf/validate/validate.proto";

message ResetPasswordRequest {
  string email = 1 [(buf.validate.field).string.email = true];
  string code = 2 [(buf.validate.field).string.pattern = "^[0-9a-zA-Z]{6}$"];
  string new_password = 3 [
    (buf.validate.field).string.min_len = 6,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-zA-Z0-9!@#$%^&*_]+$"
  ];
}

enum ResetStatus {
  RESET_STATUS_UNSPECIFIED = 0;
  RESET_STATUS_SUCCESS = 1;
  RESET_STATUS_INVALID_CODE = 2;
  RESET_STATUS_ARG_INVALID = 4;
  RESET_STATUS_USER_NOT_FOUND = 5;
}

message ResetPasswordResponse {
  ResetStatus status = 1;
  int32 user_id = 2;
}

service ResetService {
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
}
