syntax = "proto3";
package oj.demo.user.v1;

import "oj/demo/user/v1/user.proto";

enum UpdateStatus {
  UPDATE_STATUS_SUCCESS_UNSPECIFIED = 0;
  UPDATE_STATUS_ARG_INVALID = 1;
}

message UpdateAvatarRequest {
  string filename = 1;
  bytes data = 2;
  string mime_type = 3;
}

message UpdateProfileResponse {
  UpdateStatus status = 1;
  UserProfile profile = 2;
}

message GetProfileRequest {
  int32 user_id = 1;
}

enum GetProfileStatus {
  GET_PROFILE_STATUS_SUCCESS_UNSPECIFIED = 0;
  GET_PROFILE_STATUS_NOT_FOUND = 1;
  GET_PROFILE_STATUS_PERMISSION_DENIED = 2;
}

message GetProfileResponse {
  UserProfile profile = 1;
}

service UpdateProfileService {
  rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
  rpc UpdateProfile(UserProfile) returns (UpdateProfileResponse);
  rpc UpdateAvatar(UpdateAvatarRequest) returns (UpdateProfileResponse);
}
