syntax = "proto3";
package oj.demo.question.v1;

message Question {
  int32 id = 1;
  string title = 2;
  string content = 3;
  int64 create_time = 4;
  int64 update_time = 5;
  optional int64 delete_time = 6;
}

message TestInstance {
  int32 id = 1;
  int32 question_id = 2;
  int32 sort = 3;
  string input = 4;
  string output = 5;
  int64 create_time = 6;
  int64 update_time = 7;
  optional int64 delete_time = 8;
}

enum SubmissionStatus {
  SUBMISSION_STATUS_UNSPECIFIED = 0;
  SUBMISSION_STATUS_PENDING = 1;
  SUBMISSION_STATUS_SUCCESSED = 2;
  SUBMISSION_STATUS_TIMEOUT = 3;
  SUBMISSION_STATUS_RUNTIME_ERROR = 4;
  SUBMISSION_STATUS_COMPILE_ERROR = 5;
  SUBMISSION_STATUS_WRONG_ANSWER = 6;
  SUBMISSION_STATUS_MEMORY_LIMIT_EXCEEDED = 7;
  SUBMISSION_STATUS_INTERNAL_ERROR = 8;
}

enum SubmissionLanguage {
  SUBMISSION_LANGUAGE_UNSPECIFIED = 0;
  SUBMISSION_LANGUAGE_JAVA = 1;
  SUBMISSION_LANGUAGE_GO = 2;
  SUBMISSION_LANGUAGE_PYTHON = 3;
}

message Submission {
  int32 id = 1;
  int32 question_id = 2;
  int32 user_id = 3;
  string code = 4;
  SubmissionLanguage language = 5;
  SubmissionStatus status = 6;
  int32 total_test_instances = 7;
  int32 passed_test_instances = 8;
  TestInstance fail_test_instance = 9;
  string message = 10;
  int32 time_cost = 11;
  int32 memory_cost = 12;
  int64 create_time = 13;
  int64 update_time = 14;
  optional int64 delete_time = 15;
}
