syntax = "proto3";
package oj.demo.user;
option java_package = "oj.demo.user.api.reset";
option java_multiple_files = true;

enum AccountType {
    ACCOUNT_TYPE_ID = 0;
    ACCOUNT_TYPE_EMAIL = 1;
}

message ResetRequest {
    AccountType type = 1;
    string code = 2;
    string new_password = 3;
    int64 timestamp = 4;
    int32 nonce = 5;
}

enum ResetStatus {
    RESET_STATUS_SUCCESS = 0;
    RESET_STATUS_INVALID_CODE = 1;
    RESET_STATUS_EXPIRED_CODE = 2;
    RESET_STATUS_ARG_INVALID = 3;
}

message ResetResponse {
    ResetStatus status = 1;
    int32 user_id = 2;
}

service ResetService {
    rpc ResetPassword(ResetRequest) returns (ResetResponse);
}